burningalchemist/sql_exporter

cmd/sql_exporter/main.go, cmd/sql_exporter/promhttp.go, collector.go, config/config.go, go.mod, go.sum, query.go, sql.go
- Replace unmaintained glog library with compatible and active [klog](https://github.com/kubernetes/klog). The idea is also to adopt k8s [logging conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md);
- Add additional log message, which hopefully fixes #14, at least should provide some clarity during debugging. It's accessible with `-v 3`;
- Reworded some log messages.
=> refactor: replace glog with klog

.github/workflows/build.yml, .promu.yml, Makefile
- promu.yml: Update Promu configuration to use Go v1.17 for builds;
- Makefile: Fix `go get` deprecation warning when installing `promu`, which is outside of the main module. Use `go install github.com/prometheus/promu@v0.12.0` with a pinned version instead.
=> build: support Go 1.17

exporter.go
fixes #56 
Add `SQLEXPORTER_TARGET_DSN` environment variable to override target DSN.
=> fix: add env variable for dsnOverride flag

cmd/sql_exporter/main.go
To avoid potential confusions with other software, we add prefix for the following variables.
```
"DEBUG" -> "SQLEXPORTER_DEBUG"
"CONFIG" -> "SQLEXPORTER_CONFIG"
```
Given that `CONFIG` variable might be actively used, so far it's deprecated, and will be removed in the next release.
=> refactor: change env vars for debug and config params

cmd/sql_exporter/promhttp.go
Revert changes from #74 and address the actual security recommendation, since the input is already sanitised on the `net/http` side.
fixes #73
=> fix: revert and address user-driven log injection issue

cmd/sql_exporter/main.go
We want to count number of scrapes by HTTP status code for the main handler (`/metrics`). This might help identify issues, also detect the moment when data collection is flaky or doesn't work at all.
=> fix: instrument requests to the main handler correctly

README.md, cmd/sql_exporter/main.go, config/config.go, go.mod, go.sum
Integrate TLS/BasicAuth features provided in the `exporter-toolkit/web` [package](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md).
User is supposed to provide a separate YAML file, that might contain TLS certificate and key file paths for a server to operate with HTTPS. We can also set certificate verification, which enables TLS client authentication. In this case, the connected clients should be issued by a known Certificate Authority (CA).
Alternatively, we can use usernames and hashed passwords that have full access to the web server via Basic Authentication. If empty, no basic authentication is required. Passwords are hashed with `bcrypt`.
Basic Authentication is meant for simple use cases, with a few users. If we need to authenticate a lot of …
=> feat: add TLS/BasicAuth via exporter-toolkit/web

cmd/sql_exporter/main.go
These flags refer to `go-kit/log`, which seems to become our replacement for `klog`.
- `-log.json` - to write logs in JSON instead of `logfmt`;
- `-log.level` - to set log level (currently `debug` by default, as we use klog-gokit bridge).
=> feat: add flags to write json logs, to set log level

config/config.go
For more details see Go 1.16 release notes at
https://go.dev/doc/go1.16#ioutil
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
=> chore: remove deprecated io/ioutil package usage

Dockerfile
Update Dockerfile to stay compliant with Prometheus community decisions, like:
- use a minimal busybox image (comes with `uclibc`);
- run as `nobody` user;
- minor changes to MAINTANER/LABEL statement.
=> build: update Dockerfile

cmd/sql_exporter/main.go
As we currently use `klog-gokit` as a bridge between `klog` and `gokit/log`, the number of supported levels there is limited. We don't want to log too much by default, however we also need to indicate that the exporter started correctly. In this circumstance, we set log level for init messages to `Warning`.
Once we migrate to `gokit/log`, we can revisit log levels.
=> fix: set default loglevel to info, update level for init msgs

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml, drivers.go, drivers_gen.go, go.mod, go.sum
`Azure Active Directory` authentication uses temporary authentication tokens to authenticate. The `mssql` package does not provide an implementation to obtain tokens: instead, import the `azuread` package and use driver name `azuresql`. This driver uses [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#section-readme) to acquire tokens using a variety of credential types.
https://github.com/microsoft/go-mssqldb#azure-active-directory-authentication
closes #138
=> feat: import azuread (also imports regular driver)

cmd/sql_exporter/main.go, go.mod, go.sum
Address CVE-2022-46146
Note: as a side-effect upgrade Prometheus Exporter-Toolkit as well, related dependabot bump https://github.com/burningalchemist/sql_exporter/pull/166
=> fix: address CVE-2022-46146

.promu.yml
Promu: create builds for Apple M1 Silicon
=> chore: add darwin/arm64 arch to promu

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> build: Update actions/setup-go and actions/checkout to v3

README.md, config/config.go, examples/sql_exporter.yml
This PR implements support for glob patterns (see linked issue) in the `collectors` configuration of `target` (and `jobs`).
This change is _almost_ non-breaking because glob patterns without matching terms act as exact string matchers, i.e. the previous behaviour for the `collectors` configuration. However, the catch is that users using matching terms, e.g. `*`, `?`, `[`, `]` or `^`, in their collector names (a very unlikely but possible case) must now escape those characters.
The implementation is not _perfectly_ efficient as it adds an inner `for`-loop and uses a `map` during collector resolving to ensure that collectors matching multiple patterns are only added once to the output `resolved` array. However, I don't think this is a big issue in practice. In any case let me know if you …
=> feat: add globbing support to collector refs in config

config/config.go
This PR fixes a bug when `resolveCollectorRefs()` fails immediately in nested loop
https://github.com/burningalchemist/sql_exporter/blob/dbe888fa8fda330f18732387a99a99057d0b8e06/config/config.go?plain=1#L562-L573
Which actually happens every time there is a name mismatch in the slice and the map. For example, we have 3 collector files:
```
vertica_eon.collector.yml
vertica_ops.collector.yml
vertica_platform.collector.yml
```
And the following `sql_exporter.yml` with collectors specified without globbing
```
target:
collectors:
- vertica_ops
- vertica_platform
collector_files:
- '*.collector.yml'
```
In the inner loop, the function will compare `vertica_ops` against all collector names in the map and return an error when it hits either `vertica_eon` or `vertica_platform`, which is an …
=> fix: don't fail immediately in resolveCollectorRefs nested loop

config/config.go, config/config_test.go
After my shameful programming errors in PR #194, some of them reported in #210 and fixed in #208, I decided to shield the codebase a bit against this type of mistakes by adding unit tests for the `resolveCollectorRefs()` function. In particular:
* `NoGlobbing` test: checks that non-globbed collector references are correctly resolved.
* `Globbing` test: checks that globbed collector references are correctly resolved.
* `NoCollectorRefs` test: checks that `resolveCollectorRefs()` resolves to empty when no collector references are given.
* `UnknownCollector` test: checks that `resolveCollectorRefs()` errors correctly when a collector reference is invalid.
All of the above tests (with the exception of `Globbing`) pass with the implementation in `0.9.3` (before globbing support).
Only the …
=> add unit tests and minor fixes for `resolveCollectorRefs()`

.github/workflows/release.yml, Dockerfile.multi-arch, Makefile
As there's a demand to have arm64 images in #218, we need to:
- provide platform list when building with `docker buildx build --platform=...`
- cross-compile the application to run on a respective platform
This PR introduces `Dockerfile.multi-arch` along with the updated Github Actions workflow to produce and push images for `linux/amd64` and `linux/arm64` (and potentially, other platforms too). We also keep original `Dockerfile` for compatibility and regular scenarios.
In addition, we need to use `docker/setup-qemu-action@v2` step to address multi-arch build issues and emulate platforms when cross-compiling.
- https://docs.docker.com/build/building/multi-platform/
=> build: containers via multi-platform Dockerfile

config/config.go, query.go
Add this for cases when the backend does not support it
=> feat: add ability to not prepare statements

packaging/rpm/sql_exporter.service
- Fix `log.level` typo in the systemd service for rpm package;
- Fix wrong environment file location in the systemd service for rpm package.
Fixes #242
=> fix: typo and wrong file reference for rpm

README.md
- We need to change special characters (like `#`) to their URL-encoded variants (`%23`) to avoid issues with DSN parsing; 
- Minor formatting changes
fixes #241
=> docs: Update README.md on the special characters

examples/sql_exporter.yml
Prior to this patch, the first comment in `examples/sql_exporter.yml`:
```
```
This was confusing to me, as the mentioned `scrape_timeout` is not present in the file. This patch should save someone else the 5 mins of head scratching
=> Include scrape_timeout in the example sql_exporter.yml

README.md, config/config.go, go.mod, go.sum
This change allow AWS users, to store the database credentials  in AWS Secret manager instead of adding the credentials in the configuration file directly. 
Changes:
- Adding a new config `aws_secret_name` under `target` to store the data source name (DSN) which has the database connection info. 
- Update the config.go to read the DSN from the given secret in the configuration file.
- Update the config.go to override the DSN from AWS secret manager. 
- Update README file with the steps to use AWS Secret manager.
=> feat: add AWS Secret Manager feature to store DSN

README.md
=> docs: add multiple connections section, formatting

sql.go
To be able to connect to Azure SQL database instances with AAD, we need to use `GoDriver` value if it's populated, when passing `driverName` to the `sql.Open` function, so `azuresql` is passed instead of `sqlserver`. The logic has been introduced in dburl v0.16 to address azuresql-related issues.
fixes #138
=> fix: adopt driver-picking logic from dburl 0.16

cmd/sql_exporter/main.go, config/config.go, exporter.go, target.go
fixes #303
This PR enables `up` (availability) and `scrape_duration` metrics for a single target if `target.name` is populated in the config.
Currently, the label `instance` is populated with target's name, which might look confusing. Given the fact that `jobs` also use `instance` for target names, we'll schedule the label change for both to `v0.13` for compatibility reasons.
=> fix: enable up and duration for target if named

cmd/sql_exporter/main.go, config/config.go, job.go, target.go
=> refactor: 'instance' label replaced by 'target', is configurable

config/config.go, metric.go
There are situations when we want to return some string data from the query (to re-process it later on the Prometheus side), and there's no value columns that could represent float64 number as a metric value. Even though we can solve it with some SQL adjustments, it's not always clear, when we look at SQL statements alone. It's also possible, that we simply cannot add a additional dummy value column due to different constraints (e.g. stored procedures we can't change) to point `values` parameter to.
To address this problem, we introduce metric configuration field `static_value` which can be set to a fixed number. The result is that we focus on the information mapped to `key_labels` instead, the value itself doesn't need to mean anything (although, the commonly used value would be `1`) and …
=> feat: set 'static_value' per metric config

cmd/sql_exporter/main.go, cmd/sql_exporter/promhttp.go, cmd/sql_exporter/util.go, collector.go, config/config.go, exporter.go, job.go, metric.go, query.go, target.go
- Total number of scrape errors per job, target, collector and query. It's enabled if a target name is defined (for a single target). For jobs it's available automatically (since target names are populated automatically).
resolves #256
=> feat: scrape_errors_total metric

.github/workflows/helm-workflow.yaml, helm/.helmignore, helm/Chart.yaml, helm/ci/helmfile.yaml, helm/ci/postgresql-values.yaml, helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/configmap.collectors.yaml, helm/templates/deployment.yaml, helm/templates/secret.configuration.yaml, helm/templates/service.yaml, helm/templates/servicemonitor.yaml, helm/templates/tests/test-connection.yaml, helm/templates/tests/test-servicemonitor.yaml, helm/values.yaml
Hi!
I thought of starting to use `sql_exporter` on k8s, but I found out that there was no helm chart available, so I've decided to come up with one.
This PR contains the helm chart and the new GitHub action that will lint, test and release that chart. The release action requires GitHub pages enabled, because it's using it as a helm repository, you can check it in my fork: https://github.com/allanger/sql_exporter/tree/gh-pages
In this PR, release is enabled only when the action is triggered by pushing to the master, but since the action is checking if there were changes to the chart before releasing, it will require one more commit with a version bump to release the first version. 
When the new chart version is released, it will be put to GitHub releases and GitHub pages branch will be …
=> feat: add a helm chart with the releaser action

collector.go, exporter.go, metric.go, query.go, target.go
=> fix: don't cache invalid metrics

helm/Chart.yaml
It's required now without any actual changes to the chart to trigger the
first release. The releaser tool will compare the state to previous
master and trigger a release. It will be uploaded to GitHub releases of
the project and also it should create a file index.yaml that should be
pushed to the gh-pages branch. This branch should also be the one that
is used for the GitHub Pages feature. And it should be done before
merging this PR to the master.
The easiest way to create it would be
$ git checkout --orphan gh-pages
$ git rm --cached -r  .
$ git clean -f -d .
$ git commit --allow-empty -m "Init GitHub pages branch"
$ git push --set-upstream origin gh-pages
Then go to GitHub project settings -> Pages -> Choose the branch to
deploy from. After it's done, this commit should be merged to …
=> chore: Update the helm chart version for the first release

.github/workflows/helm-workflow.yaml, helm/Chart.yaml
I hope these rules will work as expected.
Now when a PR is created there must be a new action that is linting and testing the chart. It should detect changes, so if it doesn't I'll check what else is wrong. 
If changes are detected and changes are passed, it should trigger the release only when merged to the master
=> build: update helm-chart workflow

.github/workflows/helm-workflow.yaml, helm/Chart.yaml
I've added a step to the helm-workflow, that is adding an annotation to the helm chart manifests. This annotations contains a SHA of a current commit. If the action is triggered by puhsing to the master, this annotations will be preserved and will make it to the upstream manifests, though it's not visible in the git repo.
I'm adding to identify the the commit to which we should compare the current version of the chart. If it's not accessible, the chart will be compared to the previous commit, that basically means that there is no released version yet.
I've also added a repo URL to chart annotations, so we can get the chart from the upstream repo to retrieve the SHA annotations from the upstream chart. It should make it possible to use the same workflow in forked repos, if an intention …
=> build: Compare current chart to latest released

.github/workflows/helm-workflow.yaml, helm/Chart.yaml, helm/templates/NOTES.txt
We need to use some features that are available only in the main branch at the moment. So until the next version is released, I'd suggest switching to the main revision.
Also, I've removed a notice about helm tests from NOTES.TXT, because we are not rendering tests anymore by default, and hence this note might be confusing
=> build: Switch helm-releaser to the main branch

helm/Chart.yaml, helm/README.md, helm/README.md.gotmpl, helm/values.yaml
Adding `scrapeTimeout` with random value broke things:
```
error="scrapeTimeout \"60s\" greater than scrapeInterval \"15s\""
```
It's better to leave scrapeTimeout unset (was some sane commented out default).
=> fix(helm): scrapeTimeout and interval clash, release v0.2.2

cmd/sql_exporter/main.go, config/config.go, query.go
resolves #400
When set to true, errors on the missing values for the requested columns are reported at Info (Debug in the `klog-gokit` translation) log level, invisible by default.
Setting this flag on reduces the amount of noisy log messages users are aware of (check the original user story). The metric with missing labels doesn't get collected nor reported as an invalid metric. Off by default.
=> fix: add flag to ignore results with missing values

sql.go
fixes #427 
os.ExpandEnv by default returns empty string if the variable is unavailable. This might create issues for users trying to debug configuration. Instead, we return the initial variable untouched as a fallback.
=> fix: expand env vars while parsing DB URL

README.md, config/metric_config.go, documentation/sql_exporter.yml, metric.go, query.go
resolves #351
Introduce `timestamp_value` field for the metric configuration. If it points at the column containing a valid timestamp, this timestamp will be collected to return a [metric with a timestamp](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#NewMetricWithTimestamp) such as:
```
test{Username="jenkins46",target="test",test="Identifier"} 4 1328099743000
```
=> feat: return metric with an explicit timestamp from the configured column

query.go
By default, empty yaml field resolves to empty string, which might create unexpected issues. We want simply check if the field is set, and if not - ignore reserving the column for it.
It's an oversight.
=> fix: if timestamp_value is empty, no need to reserve a column

README.md
Fix DSN example for PostgreSQL db in Readme + fix yaml indentation (2 spaces per level).
=> docs: Fix PostgreSQL DSN example [skip ci]

README.md, cmd/sql_exporter/main.go, cmd/sql_exporter/promhttp.go, exporter.go, job.go, target.go
resolves #178 
We can call the endpoint with the query parameter `jobs[]` to scrape only selected jobs:
```
localhost:9399/metrics?jobs[]=dbtargets1&jobs[]=dbtargets2
```
In Prometheus configuration we can use this syntax under the [scrape config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cscrape_config%3E):
```yaml
...
params:
jobs[]:
- dbtargets1
- dbtargets2
...
```
=> feat: scrape selected jobs via query params

helm/Chart.yaml, helm/README.md, helm/README.md.gotmpl, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/secret.configuration.yaml, helm/values.yaml
This is a PR that is supposed to cover both
- https://github.com/burningalchemist/sql_exporter/pull/432
- https://github.com/burningalchemist/sql_exporter/pull/397
I haven't added new tests, I think it might make sense, but I would first wait for a @burningalchemist opinion in the approach
=> feat(helm): add an ability to mount extra volumes

README.md
We faced some challenges with our team trying to include information in our jobs that had multiple targets, and couldn't use the static_labels in collectors in this specific case.
We were relying on the `job_name`, but it didn't seem like the best approach. After doing some research, we discovered that _sql_exporter_ actually **already** had a feature to address this issue, even though it wasn't documented. 
We've made a small addition to the README to help out any future users who may encounter the same issue as us.
=> docs(README): mention the feature of labels for multiple targets in jobs [skip ci]

Makefile
Given that some commands in the Makefile are unix-specific, it becomes complicated to build sql_exporter on Windows without using WSL or similar subsystems (e.g. Cygwin).
This PR creates Windows overrides for crucial commands.
=> build: update Makefile to support native Windows builds

go.mod
CodeQL complains:
> As of Go 1.21, toolchain versions [must use the 1.N.P syntax](https://go.dev/doc/toolchain#version).
> 
> 1.21 in go.mod does not match this syntax and there is no additional toolchain directive, which may cause some go commands to fail.
=> fix: update gomod version to fix codeql warnings

.github/workflows/release.yml, Dockerfile.multi-arch
To have consistent builds we want to make sure Go version is the same for all the builds. It wasn't a problem before `v1.22`, but it seems to be a good opportunity to improve consistency these days.
- Update Dockerfile.multi-arch so it takes a build argument (with `latest` being a default value) that we can pick from `.promu.yml`;
- Add a step to GitHub actions to obtain the version from the config file, and store it in the step output key.
- In the future we might want to drop building binaries again and reuse ones built by promu crossbuild. So the Dockerfile will be changed, the builds also should become faster.
=> fix(build): sync go versions between promu crossbuild and docker images

helm/Chart.yaml, helm/README.md, helm/templates/deployment.yaml
This was causing an issue where it couldn't properly decode extra volume mounts due to the indentation being out of alignment: 
```
Error: YAML parse error on sql-exporter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 48: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 48: did not find expected key
```
=> fix: indentation of  extra volume mounts in deployment.yaml

helm/Chart.yaml, helm/README.md, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/serviceaccount.yaml, helm/values.yaml
Enable extra containers and service account customization  to facilitate running a sql auth proxy as a sidecar.  The service account customization was necessary to enable alternative authentication methods such as workload identity.
Please squash when merging.
=> feat(helm): Sidecar and Service Account Update

helm/Chart.yaml, helm/README.md, helm/README.md.gotmpl, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/serviceaccount.yaml, helm/values.yaml
- `serviceAccount` field is deprecated in favour of `serviceAccountName`;
- `serviceAccount.create` should create a serviceAccount resource bound to the helm release name (which can be overriden, yet is consistent);
- `serviceAccount.name` should allow users to reference a custom service account created outside of the helm release;
- if `create` is false, and name is not set, `serviceAccountName` field falls back to `default` which is equal to not providing the `serviceAccountName` at all.
BREAKING CHANGE: from v0.5.0 serviceAccount `sql-exporter` is created by default. Can be disabled if needed to reference a custom serviceAccount object.
=> fix!(helm): adjust the logic for serviceAccount creation

.gitignore, README.md, documentation/sql_exporter.yml
Fix the explanation of the argument -config.file string
SQL Exporter configuration file name. (default "sql_exporter.yml")
It should be: SQL Exporter configuration file path. (default "sql_exporter.yml")
And some typos.
=> docs: Update Readme and Doc [skip ci]

helm/Chart.yaml, helm/README.md, helm/templates/servicemonitor.yaml, helm/values.yaml
if I set `serviceMonitor.namespace`, it overrides the namespace where the ServiceMonitor is deployed. However, the pod is deployed in the same namespace, so I'd like this to override the namespace in `matchNamespace` spec field also.
=> fix(helm): ServiceMonitor namespace override

documentation/sql_exporter.yml, examples/sql_exporter.yml
Getting invalid URL error because of this. Found the solution in `https://github.com/xo/dburl` documentation.   
The example database connection URL that can be handled by `dburl.Parse` and `dburl.Open`:
`sqlserver://user:pass@remote-host.com/dbname`
I think we need to provide dbname in data_source_name
=> docs: update data_source_name in configuration file

helm/Chart.yaml, helm/README.md, helm/templates/deployment.yaml, helm/values.yaml
- Allow configuration of liveness and readiness probes
- Defaults might be too stringent in certain environments causing unnecessary pod restarts
=> feat(helm): configure liveness and readiness probes

cmd/sql_exporter/main.go
This pull request includes removing the deprecated `log.json` flag and updating the `setupLogging` function accordingly.
Now the only possible way to set up the log format is by using `--log.format` parameter with `logfmt` or `json` as allowed values.
=> refactor: remove deprecated --log.json flag

.promu.yml
This pull request includes a minor update to the `.promu.yml` configuration file, specifically updating the Go language version.
* [`.promu.yml`](diffhunk://#diff-76a63a7d40d9c5b7f57eed5b30dd49aaa623ad3d151a7846ffeca93f08db0eb8L3-R3): Updated the Go version from `1.21` to `1.23`.
=> build(promu): set go version to 1.23

packaging/conf/sql_exporter.default, packaging/deb/sql_exporter.service, packaging/rpm/sql_exporter.service
This pull request includes changes to the logging configuration for the SQL Exporter service. The primary update is the switch from JSON logging to logfmt format across different configuration files.
Logging configuration changes:
* [`packaging/conf/sql_exporter.default`](diffhunk://#diff-ad3e6f08166545f5de24ef29da8a44dde44e9369144a888e15bc9b762393aa46L3-R3): Changed `LOG_JSON=false` to `LOG_FORMAT=logfmt` to update the logging format.
* [`packaging/deb/sql_exporter.service`](diffhunk://#diff-487da9683d07d225f3b70cab8f4acd6bdb657bddd5c362840b7b983143a3d52dL16-R16): Updated `ExecStart` command to use `-log.format=${LOG_FORMAT}` instead of `-log.json=${LOG_JSON}` for the Debian service configuration.
* [`packaging/rpm/sql_exporter.service`](diffhunk://#diff-6c612085e57c7935f6a670f78dc129cc46 …
=> fix(packaging): update -log.format parameter for deb/rpm config

go.mod
CodeQL complains about go.mod file, as it doesn't follow the new syntax (https://go.dev/doc/toolchain#version)
=> fix(gomod): follow 1.N.P syntax

README.md
This pull request includes a short update to the `README.md` file, adding new instructions for using WinSSPI or NTLM as the authentication mechanism for MSSQL.
=> docs: add WinSSPI/NTLM connection options

go.mod, go.sum
=> fix(security): Bump golang.org/x/net from 0.30.0 to 0.33.0

helm/Chart.yaml, helm/README.md
This pull request includes version updates for the `sql-exporter` Helm chart and its documentation.
Version updates:
* [`helm/Chart.yaml`](diffhunk://#diff-ab3e9fcf0ffe762ed2805586f2e116f0c38db08c3b34d6ba2cfa90e871a1d918L5-R6): Updated the `version` to `0.10.1` and `appVersion` to `0.17.0`.
* [`helm/README.md`](diffhunk://#diff-ba66b531f5db27e2cb364be1b4cda073681f7447f088ac98139ca96c1609dc16L3-R3): Updated the version badge to reflect the new `version` and `appVersion`.
=> Bump up helm chart to 0.10.1

helm/Chart.yaml, helm/README.md, helm/templates/ingress.yaml, helm/values.yaml
Some time ago, I wanted to add support for Ingress in SQL Exporter, but I was beaten to it in #640 :) However, after the introduction of Ingress support, I was missing just one thing – the ability to set the value of the path parameter. This PR adds that capability.
=> feat(helm): Add path support for ingress in the helm chart

helm/Chart.yaml, helm/README.md, helm/templates/deployment.yaml, helm/values.yaml
Kubernetes 1.29+ now supports sidecars containers: https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
Add support `initContainers` as a field on the chart.
=> feat(helm): add support for initContainers on the chart

.github/workflows/build.yml, .github/workflows/release.yml, .promu.yml, go.mod
This pull request updates the Go version used across the project to ensure compatibility with the latest features and improvements. The changes affect the workflow configurations, project settings, and module dependencies.
=> build: update go version to 1.24+, remove toolchain directive

README.md, cmd/sql_exporter/main.go
Introduce a new command-line flag to validate the configuration before starting the SQL exporter.
This Flag could be used to validate main configuration yaml and possible collector ones in a github-action pipeline before deployment
=> feat: add -config.check flag for configuration validation

.github/workflows/release.yml
This pull request updates the version of the GitHub Action used for releasing artifacts in the `.github/workflows/release.yml` file.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L47-R47): Updated the `softprops/action-gh-release` action from version `v2` to `v2.2.2` to ensure compatibility and access to the latest features and fixes.
=> build: pin gha gh-release to v2.2.2

query.go
This pull request includes a minor change to the logging level in the `scanRow` method of the `query.go` file. It adjusts the log level from `Warn` to `Debug` for cases where key, time, or value columns are `NULL`. This should reduce the amount of unnecessarily rendered logs.
* [`query.go`](diffhunk://#diff-66f9c6b00ef4ad1dbef1133865440121c8d03aec3333e8b6dd97ac3560b91ac7L216-R226): Changed the log level from `slog.Warn` to `slog.Debug` for better granularity when logging `NULL` values in key, time, and value columns within the `scanRow` method.
=> fix: move NULL messages under Debug log level

config/config.go, config/target_config.go, config/util.go, exporter.go
This pull request introduces improvements to code readability, functionality, and documentation across several files in the project. Key changes include adding package-level comments, improving code clarity by replacing nested loops with utility functions, and ensuring consistent naming conventions.
* Added package-level comments to `config/config.go` and `exporter.go` to provide an overview of the functionality and purpose of the respective packages. (`[[1]](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R1-R2)`, `[[2]](diffhunk://#diff-e4987a222ab3e846614998485952d8ee42288062a30929290cf3ea0e815d5ae1R1-R12)`)
* Replaced nested loops with the `slices.Contains` utility function to simplify duplicate checks in `config/util.go` and target filtering in …
=> refactor: address linter warnings, apply gopls recommendations
