target.go
fixes #27 
When we use cacheCollector (by setting `min_interval` in the configuration), we expect to only return cached results from `sql_exporter` or fresh metrics from the database when it's time to get some.
Currently, while scraping cached metrics, we still ping the remote database, which is suboptimal. It's not a big issue for typical RDBMS solutions like MySQL or PostgreSQL, although it still produces unnecessary noise. However, for paid database services, this might lead to unexpected and useless charges.
For example, hitting `/metrics` endpoint 3 times in a row and getting cached metrics for SnowflakeDB results with 3 `SELECT 1` calls, which implies that the warehouse will always be up and running:
That might be expensive.
By introducing `--config.enable-ping` (which is `true` by …
=> fix: add config.enable-ping flag

cmd/sql_exporter/promhttp.go
=> fix: address CWE-117 security issue

config/config.go, errors/errors.go, sql.go
https://tip.golang.org/doc/go1.19
Doc Comments formatting has changed.
=> chore: fix formatting since 1.19

cmd/sql_exporter/content.go, cmd/sql_exporter/main.go, collector.go, config/config.go, metric.go, query.go, sql.go, target.go
* Remove `pprof` package as it might potentially leak server data (G108);
* Set ReadHeaderTimeout value for http server to avoid potential Slowloris Attack (G112);
* Remove completed TODOs;
* Fix useless comments;
* Apply `gofumpt` formatting.
=> chore: golangci-lint findings

packaging/conf/nfpm.yaml, packaging/deb/sql_exporter.service, packaging/rpm/sql_exporter.service
`/usr/local/bin` is for user programs _not_ managed by the package manager. So we need to change the directory to `/usr/bin` for the packages.
=> fix: nfpm - update binary path for packages

go.mod, go.sum
Support 'azuresql' scheme alias for Azure AD
=> deps: update xo/dburl to 0.12.2

config/config.go
This PR fixes exporter panics on two config corner cases (see linked issues).
Let me know of any feedback!
Fixes #182
Fixes #183
=> fix: exporter panics on config corner cases

sql.go
Currently `dburl` dependency handles `azuresql` scheme as `sqlserver` alias and assigns it as a driver name. To use Azure AD the upstream driver expects strictly `azuresql` as a driver name. We detect `fedauth` in a query string, and set the expected driver name correctly.
This might be fixed later in the upstream dependency and removed here.
fixes #169
=> fix: detect fedauth for AzureSQL and assign a correct driver name

.github/workflows/release.yml
=> feat: build arm64 container images

sql.go
- Remove FIXME workaround as it was addressed in #223 in the upstream dependency.
=> fix: handling is fixed in the upstream dburl

go.mod, go.sum
=> deps: update dburl to v0.16.0

cmd/sql_exporter/promhttp.go
=> fix: wrap remaining errors in klog.Errorf()

cmd/sql_exporter/promhttp.go
fixes #164 
This PR should help to mitigate the `context deadline exceeded` case in the short run;
Once we've switched minimum Go version to `v1.20` in `go.mod`, we can start using `context.Cause()` function to propagate better context-related messages.
=> fix: return better error msg on context deadline exceeded

target.go
=> fix: regression, don't overwrite constLabels

.promu.yml
=> chore: update Go to 1.21 as the main version

cmd/sql_exporter/promhttp.go, errors/errors.go, go.mod, go.sum
=> fix: revisit errors package, match the error

.github/workflows/helm-workflow.yaml
relates to https://github.com/helm/chart-testing-action/issues/132
=> build: bump helm/chart-testing-action to 2.6.0

metric.go, query.go
=> fix: support NULL metrics, don't collect them

README.md
Reverts burningalchemist/sql_exporter#434
=> Revert "docs: Fix PostgreSQL DSN example [skip ci]"

.github/workflows/helm-workflow.yaml
Just to introduce some clarity between the ordinary and helm chart releases.
=> fix(helm): update release name for helm charts

.github/workflows/helm-workflow.yaml, helm/.helmignore
Exclude development files from the release chart archive.
=> fix(helm): update .helmignore [skip ci]

cmd/sql_exporter/main.go, exporter.go, reload.go, target.go
=> refactor: Reload targets and collectors, support SIGHUP

cmd/sql_exporter/main.go, config/global_config.go, documentation/sql_exporter.yml, exporter.go, reload.go
=> feat: drop scrape_errors_total metric with a configurable interval

helm/Chart.yaml, helm/README.md, helm/templates/deployment.yaml, helm/values.yaml
fixes https://github.com/burningalchemist/sql_exporter/issues/605
=> feat(helm): add ability to activate -web.enable-reload flag

helm/Chart.yaml, helm/README.md, helm/templates/deployment.yaml, helm/values.yaml
This pull request includes several updates to the Helm chart for the `sql-exporter` application, focusing on version upgrades and configuration enhancements. The most important changes include version updates in the `Chart.yaml` and `README.md` files, the addition of new configuration options for logging, and corresponding updates to the deployment template and values file.
* [`helm/Chart.yaml`](diffhunk://#diff-ab3e9fcf0ffe762ed2805586f2e116f0c38db08c3b34d6ba2cfa90e871a1d918L5-R6): Update the `version` to 0.9.0 and `appVersion` to 0.16.0.
* [`helm/README.md`](diffhunk://#diff-ba66b531f5db27e2cb364be1b4cda073681f7447f088ac98139ca96c1609dc16L3-R3): Update the badges to reflect the new `version` and `appVersion`.
* [`helm/README.md`](diffhunk://#diff-ba66b531f5db27e2cb364be1b4cda073681f7447f …
=> feat(helm): add logFormat and logLevel params, update app version

helm/Chart.yaml, helm/README.md, helm/README.md.gotmpl, helm/templates/_helpers.tpl, helm/templates/ingress.yaml, helm/templates/secret.tls.yaml, helm/values.yaml
Hello,
I have added an ingress to the helm chart, making the exporter accessiable to the outside world.
It's a simple, but affective change.
=> feat(helm): Add ingress to the helm chart

drivers.go, drivers_gen.go, go.mod, go.sum
A follow up PR to the #575 (only the driver part).
=> feat: add go-ora/v2 driver

examples/postgres-16.yml
Adds example config for postgres 16.
=> docs: add example configuration for PostgreSQL 16

.github/workflows/helm-workflow.yaml, helm/Chart.yaml
`platformHooks` are supported since v3.18, so `helm-diff` expects a compatible version.
=> build(helm): Update HELM_VERSION to 3.18.6
